name: Continues Delivery
on:
  push:
    branches:
      - 'main'
jobs:
  push-to-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Set up http-client.private.env.json
        env:
          token: ${{ secrets.TOKEN }}
          demo_ds_password: ${{ secrets.DEMO_DS_PASSWORD }}
          demo_ds_user: ${{ secrets.DEMO_DS_USER }}
          demo_ds_schema: ${{ secrets.DEMO_DS_SCHEMA }}
          demo_ds_url: ${{ secrets.DEMO_DS_URL }}
        run: |
          echo "{
            \"production\": {
              \"token\": \"${token}\",
              \"demo_ds_password\": \"${demo_ds_password}\",
              \"demo_ds_user\": \"${demo_ds_user}\",
              \"demo_ds_schema\": \"${demo_ds_schema}\",
              \"demo_ds_url\": \"${demo_ds_url}\"
            }
          }" > http-client.private.env.json
      - name: Update definitions in Production
        env: # This is needed if you're deploying to the self-hosted dev environment with self-signed certificate
          NODE_TLS_REJECT_UNAUTHORIZED: "0"
        run: npm run update-prod
      - name: Drop secret
        run: rm http-client.private.env.json
        if: always()
